### PR TITLE
dump and replay updates

### PR DESCRIPTION
**Pull request by phoddie**
This commit contains the improvements we've made to the dump and replay features of xsnap as part of tracking down recent bug reports.

### CODE REVIEW

**Comment by mhofman** [comment]
@dckc are you able to review this? To me this seems to only affect features that are not used by our xsnap integration, so it looks safe to merge, but I'd rather have this PR reviewed by someone more familiar with this code than me.

**Comment by dckc** [comment]
I took a look; it's not at all obvious what the changes are about.

> improvements we've made to the dump and replay features of xsnap

Please elaborate a bit on the improvements, @phoddie ? What does the code do after this change that it didn't do before?

Or maybe I don't really need to know... maybe we don't use this code at all. It has no impact on the trace format that Agoric records and sends to Moddable, correct?

Or maybe @kriskowal is familiar with this stuff? or @warner ?

**Comment by mhofman** [comment]
> It has no impact on the trace format that Agoric records and sends to Moddable, correct?

My understanding is this is the code used to read the trace we produce. It's not changing the shape of the trace, just processing more of it (snapshot request), and displaying more info when dumping internals (snapshot content).

**Review by dckc — APPROVED** [review]
I think we have sufficient shared understanding to merge this now.

**Comment by mhofman** [comment]
I'll make sure this is included in my next sync of the Moddable SDK

**Pull request merged**
