### PR TITLE
feat: rebuild on external extra dep change

### PR DESCRIPTION
**Pull request by mhofman**
refs: https://github.com/Agoric/agoric-sdk/issues/9614

Add an `EXTRA_DEPS` environment to the makefile to enable agoric-sdk to trigger a rebuild if some env options change like `XSNAP_VERSION` or `CC`.

Drive-by deprecation of the `-n` command since the agoric-sdk PR will get rid of it in favor of checking the `XSNAP_VERSION` already embedded in `-v`

Tested by building both manually invoking the makefile with and without the `EXTRA_DEPS` set, and through the build script changed in agoric-sdk.

### CODE REVIEW

**Review by warner — APPROVED** [review]
huh, so this gives us the means to force a rebuild (assuming Makefile variables get overridden by environment variables, which I think is correct, for this syntax). But it doesn't embed a version in the binary. But, it's not like the stale -10 version that used to be there was doing us any good. So I think this is ok.

**Review by warner — APPROVED** [review]
Oh, now I see the -v, good.

Could you add a line that concatenates a greppable string like "xsnap version" with the -D -supplied version, and store the result in an (unused) static string? That will let us extract the version with /bin/strings (without trying to execute xsnap). I think the syntax is like:

```c
char *VERSION = "xsnap version: XSNAP_VERSION";
```

but it might involve something like `foo ## XSNAP_VERSION`

Then run /usr/bin/strings on the compiled xsnap and grep for "xsnap version:" and we should see the version string.

**Comment by mhofman** [comment]
> Could you add a line that concatenates a greppable string like "xsnap version" with the -D -supplied version

Done

```
$ strings packages/xsnap/xsnap-native/xsnap/build/bin/lin/release/xsnap-worker | grep xsnap_version
xsnap_version: 0.14.2
```

**Review by warner — APPROVED** [review]
looks good, minor nit: `xsnap-version` instead of `xsnap_version`, and a comment next to `char *VERSION` like "this static string lets "strings path/to/xsnap |grep xsnap-version" work, even without executing xsnap -v", because sooner or later somebody will notice that VERSION isn't used.

**Comment by mhofman** [comment]
> nit: `xsnap-version` instead of `xsnap_version`

I will keep the `_` as a case insensitive grep of `xsnap_version` returns all related usages.



> sooner or later somebody will notice that VERSION isn't used.

Aye!

**Pull request merged**
